### ISSUE TITLE
Should there be a reference to bower_components in node script?

### ISSUE THREAD

**Issue by jflasher** [bjornharrtell/javascript.util#10]
Looks like this was something that was picked up in 0.12.6 but seems to be breaking because it can't be found? 

```
$ node app.js 
module.js:338
    throw err;
          ^
Error: Cannot find module '../bower_components/closure-library/closure/goog/bootstrap/nodejs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/flasher/workspace/population/node_modules/turf/node_modules/turf-erase/node_modules/jsts/node_modules/javascript.util/dist/javascript.util-node.min.js:42:237)
    at Object.<anonymous> (/Users/flasher/workspace/population/node_modules/turf/node_modules/turf-erase/node_modules/jsts/node_modules/javascript.util/dist/javascript.util-node.min.js:42:339)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

@morganherlocker initially ran into this when trying to use turf.js.

**Comment by bjornharrtell** [comment]
Ouch. Thanks for reporting. Will try to reproduce/fix but is away for a week and some. Tests running with node works though so I'm surprised.

**Comment by johnknaack** [comment]
I'm currently seeing the same issue while using the [JSTS](https://www.npmjs.com/package/jsts) module.

ERROR in ./~/jsts/~/javascript.util/dist/javascript.util-node.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/closure-library/closure/goog/bootstrap/nodejs in /Users/johnknaack/Desktop/ree-js-demographics-client/node_modules/jsts/node_modules/javascript.util/dist
 @ ./~/jsts/~/javascript.util/dist/javascript.util-node.min.js 42:236-312

ERROR in ./~/jsts/~/javascript.util/dist/javascript.util-node.min.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../deps.js in /Users/johnknaack/Desktop/ree-js-demographics-client/node_modules/jsts/node_modules/javascript.util/dist
 @ ./~/jsts/~/javascript.util/dist/javascript.util-node.min.js 42:313-334

Let me know if I can provide any other info.

**Comment by morganherlocker** [comment]
PR to lock the utils version in JSTS https://github.com/bjornharrtell/jsts/pull/174

**Comment by lliss** [comment]
I can confirm that this is happening when using grunt-browserify to include a module that requires jsts.

**Comment by Nemo157** [comment]
Happens when simply trying to use `javascript.util` independently as well: 

```
$ npm install javascript.util
javascript.util@0.12.7 ..\node_modules\javascript.util
$ node
> var u = require('javascript.util');
Error: Cannot find module '../bower_components/closure-library/closure/goog/bootstrap/nodejs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\sources\node_modules\javascript.util\dist\javascript.util-node.min.js:42:237)
    at Object.<anonymous> (D:\sources\node_modules\javascript.util\dist\javascript.util-node.min.js:42:339)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)```

**Comment by brianreavis** [comment]
With everyone using bundlers of some sort these days (webpack, browserify, requirejs, etc), could this module be turned to commonjs – removing the need to put out dist files? (which would alleviate this issue)

**Comment by jflasher** [comment]
https://docs.npmjs.com/cli/shrinkwrap might also be a solution.

**Comment by lliss** [comment]
I don't really feel like shrinkwrap is a good solution in this case. I feel like the usecase there is for custom applications with many dependencies but an npm module should be able to build and run without it.

**Comment by bjornharrtell** [comment]
Ah I see the problem now (didn't quite grasp it before). The minified js in the npm package seem to be dependant on closure-library/closure/goog/bootstrap/nodejs, which I didn't expect. I did not notice because the tests downloads all dependencies. I'll try to fix it asap.

**Comment by bjornharrtell** [comment]
Think I finally got it fixed. Please reopen if issues remain.
